default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: rails_blog_development
  username: postgres
  password: password

test:
  <<: *default
  database: rails_blog_test
  username: postgres
  password: password

production:
  <<: *default
  database: rails_blog_production
  username: rails_blog
  password: <%= ENV["RAILS_BLOG_DATABASE_PASSWORD"] %>
